server:
  port: 80
  servlet:
    session:
      timeout: 10m #该值一定要配单位，且值一定要大于1分钟，不然是无效的
spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  datasource:
    url: jdbc:mysql://47.119.129.252:3306/xztx?useUnicode=true&characterEncoding=utf-8&autoReconnectForPools=true
    username: root
    password: 123456
#    password: ENC(Oya0yLaL+Z4cOegFDjKN4A==)
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
xztx:
  security:
    authentication:
      loginPage: /login/page # 重定向到登录界面
      loginProcessingUrl: /login/form # 登录表单提交的url，
      usernameParameter: name # 接收表单里的账户(如果不是username，就得重新定义)
      passwordParameter: pwd # 接收表单里的密码(如果不是password，就得重新定义)
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginResponseType: redirect # 返回结果为json格式或redirect格式
      imageCodeUrl: /image/code # 获取图形验证码地址
      mobilePage: /mobile/page # 发送手机验证码地址
      mobileCodeUrl: /code/mobile # 前往手机登录页面
      tokenValiditySeconds: 604800 # 记住我时效
mybatis:
  mapper-locations: classpath*:/mapper/*.xml # 映射xml文件
  type-aliases-package: com.xztx.dao # 映射dao层
  configuration:
    map-underscore-to-camel-case: true # 是否采用驼峰命名法
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*.xml # 映射xml文件
#  type-aliases-package: com.xztx.dao # 映射dao层
#  configuration:
#    map-underscore-to-camel-case: true